# Generated by Django 2.0.3 on 2018-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Feito'),
            preserve_default=False,
        ),
    ]
