# Generated by Django 2.0.3 on 2018-03-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Identificador'),
        ),
    ]
