# Generated by Django 2.0.3 on 2018-03-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180323_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['modified'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['modified'], 'verbose_name': 'To do', 'verbose_name_plural': "To do's"},
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='task1', max_length=200, unique=True, verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ToDo', verbose_name='To do'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crieted'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Id'),
        ),
    ]
