# Generated by Django 2.0.3 on 2018-03-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180323_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Todo', verbose_name='To do'),
        ),
    ]
